-- TB_GAME_HIGHLIGHT: 경기 하이라이트 (YouTube 영상)
CREATE TABLE TB_GAME_HIGHLIGHT (
    GAME_ID         VARCHAR2(20)   NOT NULL,
    YOUTUBE_VIDEO_ID VARCHAR2(50)  NOT NULL,
    TITLE           VARCHAR2(200),
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_GAME_HIGHLIGHT PRIMARY KEY (GAME_ID)
);
