-- TB_MEMBER: 카카오 로그인 회원
CREATE TABLE TB_MEMBER (
    MEMBER_ID    NUMBER(19)     NOT NULL,
    KAKAO_ID     VARCHAR2(50)   NOT NULL,
    NICKNAME     VARCHAR2(30)   NOT NULL,
    TEAM_CODE    VARCHAR2(10),
    ROLE         VARCHAR2(10)   DEFAULT 'USER'   NOT NULL,
    STATUS       VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UQ_MEMBER_KAKAO UNIQUE (KAKAO_ID)
);

-- 회원 PK 시퀀스
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE;
