-- TB_POST: 커뮤니티 게시글
CREATE TABLE TB_POST (
    POST_ID        NUMBER(19)     NOT NULL,
    MEMBER_ID      NUMBER(19)     NOT NULL,
    CATEGORY       VARCHAR2(10)   NOT NULL,   -- FREE / CHEER / STADIUM / PHOTO
    TEAM_CODE      VARCHAR2(10),
    TITLE          VARCHAR2(100)  NOT NULL,
    CONTENT        CLOB           NOT NULL,
    VIEW_COUNT     NUMBER(10)     DEFAULT 0 NOT NULL,
    LIKE_COUNT     NUMBER(10)     DEFAULT 0 NOT NULL,
    COMMENT_COUNT  NUMBER(10)     DEFAULT 0 NOT NULL,
    STATUS         VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,  -- ACTIVE / DELETED / HIDDEN
    CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_POST PRIMARY KEY (POST_ID),
    CONSTRAINT FK_POST_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE SEQUENCE SEQ_POST START WITH 1 INCREMENT BY 1 NOCACHE;

-- 목록 조회: 상태+생성일 정렬, 카테고리/팀 필터
CREATE INDEX IX_POST_LIST ON TB_POST (STATUS, CREATED_AT);
CREATE INDEX IX_POST_CATEGORY ON TB_POST (CATEGORY);
CREATE INDEX IX_POST_TEAM ON TB_POST (TEAM_CODE);
CREATE INDEX IX_POST_MEMBER ON TB_POST (MEMBER_ID);
