-- TB_COMMENT: 게시글 댓글 (1단계 대댓글 — PARENT_ID 가 있으면 답글)
CREATE TABLE TB_COMMENT (
    COMMENT_ID   NUMBER(19)     NOT NULL,
    POST_ID      NUMBER(19)     NOT NULL,
    MEMBER_ID    NUMBER(19)     NOT NULL,
    PARENT_ID    NUMBER(19),                       -- NULL 이면 최상위 댓글, 값 있으면 답글
    CONTENT      VARCHAR2(1000) NOT NULL,
    STATUS       VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,  -- ACTIVE / DELETED
    CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_COMMENT PRIMARY KEY (COMMENT_ID),
    CONSTRAINT FK_COMMENT_POST FOREIGN KEY (POST_ID) REFERENCES TB_POST (POST_ID),
    CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE SEQUENCE SEQ_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE;

-- 게시글별 댓글 목록 조회
CREATE INDEX IX_COMMENT_POST ON TB_COMMENT (POST_ID, CREATED_AT);
CREATE INDEX IX_COMMENT_PARENT ON TB_COMMENT (PARENT_ID);
