-- TB_POST_LIKE: 게시글 좋아요 (회원당 글 1개 — 복합 PK 로 중복 방지)
CREATE TABLE TB_POST_LIKE (
    POST_ID      NUMBER(19)   NOT NULL,
    MEMBER_ID    NUMBER(19)   NOT NULL,
    CREATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_POST_LIKE PRIMARY KEY (POST_ID, MEMBER_ID),
    CONSTRAINT FK_LIKE_POST FOREIGN KEY (POST_ID) REFERENCES TB_POST (POST_ID),
    CONSTRAINT FK_LIKE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE INDEX IX_LIKE_MEMBER ON TB_POST_LIKE (MEMBER_ID);
