-- TB_REPORT: 게시글/댓글 신고 (회원당 대상 1회 — 중복신고 방지)
CREATE TABLE TB_REPORT (
    REPORT_ID    NUMBER(19)   NOT NULL,
    TARGET_TYPE  VARCHAR2(10) NOT NULL,   -- POST / COMMENT
    TARGET_ID    NUMBER(19)   NOT NULL,
    REPORTER_ID  NUMBER(19)   NOT NULL,
    REASON       VARCHAR2(20) NOT NULL,   -- ABUSE / SPAM / SEXUAL / ETC
    CREATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_REPORT PRIMARY KEY (REPORT_ID),
    CONSTRAINT UQ_REPORT UNIQUE (TARGET_TYPE, TARGET_ID, REPORTER_ID),
    CONSTRAINT FK_REPORT_MEMBER FOREIGN KEY (REPORTER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE SEQUENCE SEQ_REPORT START WITH 1 INCREMENT BY 1 NOCACHE;

-- 대상별 신고 수 집계
CREATE INDEX IX_REPORT_TARGET ON TB_REPORT (TARGET_TYPE, TARGET_ID);
