-- TB_TEAM: KBO 구단 정보
CREATE TABLE TB_TEAM (
    TEAM_CODE   VARCHAR2(10)  NOT NULL,
    TEAM_NAME   VARCHAR2(50)  NOT NULL,
    STADIUM     VARCHAR2(50),
    TEAM_COLOR  VARCHAR2(20),
    CONSTRAINT PK_TB_TEAM PRIMARY KEY (TEAM_CODE)
);
