-- TB_BLOCK: 사용자 차단 (차단자 → 피차단자)
CREATE TABLE TB_BLOCK (
    BLOCKER_ID   NUMBER(19)   NOT NULL,
    BLOCKED_ID   NUMBER(19)   NOT NULL,
    CREATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_BLOCK PRIMARY KEY (BLOCKER_ID, BLOCKED_ID),
    CONSTRAINT FK_BLOCK_BLOCKER FOREIGN KEY (BLOCKER_ID) REFERENCES TB_MEMBER (MEMBER_ID),
    CONSTRAINT FK_BLOCK_BLOCKED FOREIGN KEY (BLOCKED_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);
