-- TB_POST_IMAGE: 게시글 첨부 이미지 (글당 최대 4장, 앱에서 제한)
CREATE TABLE TB_POST_IMAGE (
    IMAGE_ID     NUMBER(19)    NOT NULL,
    POST_ID      NUMBER(19)    NOT NULL,
    URL          VARCHAR2(300) NOT NULL,   -- 공개 경로 (예: /uploads/abc.jpg)
    SORT_ORDER   NUMBER(3)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TB_POST_IMAGE PRIMARY KEY (IMAGE_ID),
    CONSTRAINT FK_IMAGE_POST FOREIGN KEY (POST_ID) REFERENCES TB_POST (POST_ID)
);

CREATE SEQUENCE SEQ_POST_IMAGE START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IX_POST_IMAGE_POST ON TB_POST_IMAGE (POST_ID, SORT_ORDER);
