-- TB_GAME: 경기 정보
CREATE TABLE TB_GAME (
    GAME_ID         VARCHAR2(20)  NOT NULL,
    GAME_DATE       DATE          NOT NULL,
    HOME_TEAM_CODE  VARCHAR2(10)  NOT NULL,
    AWAY_TEAM_CODE  VARCHAR2(10)  NOT NULL,
    HOME_SCORE      NUMBER(3),
    AWAY_SCORE      NUMBER(3),
    STATUS          VARCHAR2(20)  NOT NULL,
    STADIUM         VARCHAR2(50),
    START_TIME      VARCHAR2(10),
    CONSTRAINT PK_TB_GAME PRIMARY KEY (GAME_ID)
);

CREATE INDEX IX_GAME_DATE_STATUS ON TB_GAME (GAME_DATE, STATUS);
CREATE INDEX IX_GAME_HOME_TEAM   ON TB_GAME (HOME_TEAM_CODE);
CREATE INDEX IX_GAME_AWAY_TEAM   ON TB_GAME (AWAY_TEAM_CODE);
