-- TB_PLAYER: 선수 정보
CREATE TABLE TB_PLAYER (
    PLAYER_ID    VARCHAR2(20)   NOT NULL,
    PLAYER_NAME  VARCHAR2(50)   NOT NULL,
    TEAM_CODE    VARCHAR2(10),
    POSITION     VARCHAR2(20),
    PLAYER_TYPE  VARCHAR2(10)   NOT NULL,
    BACK_NUMBER  VARCHAR2(5),
    BATS         VARCHAR2(5),
    THROWS       VARCHAR2(5),
    BIRTH_DATE   DATE,
    HEIGHT       NUMBER(3),
    WEIGHT       NUMBER(3),
    SCHOOL       VARCHAR2(100),
    DEBUT_YEAR   NUMBER(4),
    CONSTRAINT PK_TB_PLAYER PRIMARY KEY (PLAYER_ID)
);

CREATE INDEX IX_PLAYER_TEAM ON TB_PLAYER (TEAM_CODE);
CREATE INDEX IX_PLAYER_TYPE ON TB_PLAYER (PLAYER_TYPE);
