-- TB_GAME_SUMMARY: 경기 요약 (AI 생성 텍스트)
CREATE TABLE TB_GAME_SUMMARY (
    GAME_ID     VARCHAR2(20)  NOT NULL,
    SUMMARY     CLOB          NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_GAME_SUMMARY PRIMARY KEY (GAME_ID)
);
