-- KBO 10개 구단 시드 데이터.
-- 팀 코드는 core/KboCommon.kt KBO_TEAM_CODES 및 mobile/constants/teams.ts 와 일치.
-- 이미 존재하는 행은 갱신하지 않도록 MERGE 사용 (수동으로 일부 시드한 환경에서도 안전).

MERGE INTO TB_TEAM t USING (SELECT 'LG' AS C, 'LG 트윈스' AS N, '잠실' AS S, '#C30452' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'KT' AS C, 'KT 위즈' AS N, '수원' AS S, '#000000' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'SK' AS C, 'SSG 랜더스' AS N, '인천 SSG랜더스필드' AS S, '#CE0E2D' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'NC' AS C, 'NC 다이노스' AS N, '창원NC파크' AS S, '#1D467F' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'OB' AS C, '두산 베어스' AS N, '잠실' AS S, '#1A1748' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'HT' AS C, 'KIA 타이거즈' AS N, '광주-기아 챔피언스필드' AS S, '#EA0029' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'LT' AS C, '롯데 자이언츠' AS N, '사직' AS S, '#041E42' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'SS' AS C, '삼성 라이온즈' AS N, '대구 라이온즈파크' AS S, '#074CA1' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'HH' AS C, '한화 이글스' AS N, '대전 한화생명 볼파크' AS S, '#FC4E00' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);

MERGE INTO TB_TEAM t USING (SELECT 'WO' AS C, '키움 히어로즈' AS N, '고척 스카이돔' AS S, '#570514' AS K FROM DUAL) s
  ON (t.TEAM_CODE = s.C) WHEN NOT MATCHED THEN
  INSERT (TEAM_CODE, TEAM_NAME, STADIUM, TEAM_COLOR) VALUES (s.C, s.N, s.S, s.K);
